name: 提交选题
description: 提交一个选题
# title: ""
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        标题请使用 **`[选题类型] 文章标题`** 格式，文章标题请使用单词首字母 **大写** 的形式，选题类型和文章标题中间有一个 **空格**。
        选题类型包括:

        - 手动选题
        - 推荐选题

        完整示例: 
        - [推荐选题] The Lost Art of the Makefile
        - [推荐选题] The Lost Art of the Makefile
        - [手动选题] Linus Torvalds Uses Apple MacBook Hardware to Release Linux Kernel 5.19
        - [手动选题] Wow! Torvalds Modified Fedora Linux to Run on his Apple M2 Macbook

  - type: textarea
    id: title
    attributes:
      label: 原文标题
      description: 填写原文章的标题
      placeholder: 原文标题
    validations:
      required: true

  - type: textarea
    id: url
    attributes:
      label: 原文链接地址
      description: 填写原文章的链接地址
      placeholder: 原文链接地址
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: 版权协议
      description: 填写原文章的版权协议
      options:
        - label: CC-SA-BY
        - label: 其它公域许可证
        - label: 已获取作者授权

  - type: textarea
    id: reason
    attributes:
      label: 推荐理由
      description: 填写你的推荐理由
      placeholder:
    validations:
      required: false

  - type: dropdown
    id: difficulty
    attributes:
      label: 文章难度
      description: 选择文章的难度
      multiple: false
      options:
        - 困难
        - 一般
        - 容易

  - type: dropdown
    id: category
    attributes:
      label: 文章分类
      description: 选择文章的分类
      multiple: false
      options:
        - 新闻(news)
        - 观点(talk)
        - 技术(tech)
